### ISSUE TITLE
Comparison of results I get with those in the paper

### ISSUE THREAD

**Issue by fashionguy** [eladrich/pix2vertex.pytorch#10]
Hi, I run the model and get some results, which is not good comparised with those in the paper.
The difference is huge, I want to know where I might have done wrong.

The results in the paper:
![image](https://user-images.githubusercontent.com/49114843/105137534-6a00e980-5b2e-11eb-803a-17b9f556d4a8.png)
![image](https://user-images.githubusercontent.com/49114843/105137549-7127f780-5b2e-11eb-9f21-897cb88e73a0.png)

The results I get:
![image](https://user-images.githubusercontent.com/49114843/105137286-05458f00-5b2e-11eb-8797-d40052da96b8.png)
![image](https://user-images.githubusercontent.com/49114843/105137345-1a222280-5b2e-11eb-8f01-5a357ebdaddd.png)
![image](https://user-images.githubusercontent.com/49114843/105137396-2e661f80-5b2e-11eb-9f75-a2c194c7395f.png)

![image](https://user-images.githubusercontent.com/49114843/105137433-3f169580-5b2e-11eb-8208-271d9690e587.png)
![image](https://user-images.githubusercontent.com/49114843/105137451-49389400-5b2e-11eb-9e2b-9c28fd155381.png)
![image](https://user-images.githubusercontent.com/49114843/105137484-55245600-5b2e-11eb-8b9c-20f13faa1160.png)

**Comment by eladrich** [comment]
Hi,
I don't think you've done anything wrong, the difference you see is probably due to the fact this repo contains only the pix2vertex network without the fine details refinement, which is more challenging to port from Matlab. 

We actually explained this in the Readme:

> The [original pix2vertex repo](https://github.com/matansel/pix2vertex) was composed of three parts
>  - A network to perform the image to depth + correspondence maps trained on synthetic facial data
>  - A non-rigid ICP scheme for converting the output maps to a full 3D Mesh  
>  - A shape-from-shading scheme for adding fine mesoscopic details
> 
> 
>  This repo currently contains our image-to-image network with weights and model to `PyTorch` and a simple `python` postprocessing scheme.
>  - The released network was trained on a combination of synthetic images and unlabeled real images for some extra robustness :)

The results should look similar to those of our network in Figure 9, but with less noise.

**Comment by fashionguy** [comment]
I see, thank you for your reply so quickly.
