### ISSUE TITLE
Segmentation fault: 11

### ISSUE THREAD

**Issue by 1a11** [eladrich/pix2vertex.pytorch#4]
The thing panic after "p2v.reconstruct()"

OS: High Sierra 
CPU: AMD Ryzen 5 1500x
Python 3.7.0
Preinstalled python: 2.7.16

`
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 26 2018, 23:26:24) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pix2vertex as p2v
>>> from imageio import imread
>>> image = imread("Desktop/lebedev.jpg")
>>> result, crop = p2v.reconstruct(image)
Loading default detector weights from /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pix2vertex/../weights/shape_predictor_68_face_landmarks.dat
loading default reconstructor weights from /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pix2vertex/../weights/faces_hybrid_and_rotated_2.pth
Detection 0: Left: 297 Top: 297 Right: 759 Bottom: 759
Segmentation fault: 11
`

**Comment by eladrich** [comment]
Hi,
I would recommend running the notebook tutorial to better isolate where the segfault happened

**Comment by 1a11** [comment]
Not solved, but anyway
