### ISSUE TITLE
Mesh plot errors. 

### ISSUE THREAD

**Issue by umarmuzammil** [eladrich/pix2vertex.pytorch#6]
Hi, Thank you for releasing Pytorch version. I was hoping to have some fun but ran into some plotting issues.  
![image](https://user-images.githubusercontent.com/14996063/91640250-90b26c80-ea35-11ea-97f8-d8d42fa966d9.png)

I was wondering if you can add the code to output it as obj to actually preview the mesh in 3D packages ?

**Comment by gu-ma** [comment]
Yes, thanks for the repo, this looks very promising :) 

I have the same issue while trying to plot the result actually.

**Comment by gu-ma** [comment]
The preview seems to works in Jupyter only, so if you run the notebook (`reconstruct_pipeline.ipynb`) then you can test the detection, reconstruction and preview. 

k3d is a [Jupyter notebook extension for 3D visualization](https://github.com/K3D-tools/K3D-jupyter) so it won't work out of the box in a .py file. The example code in the readme should run in a jupyter notebook I assume.

Nevertheless it would be real nice to know how to export / save the mesh and texture 😸

**Comment by eladrich** [comment]
As explained by @gu-ma, the interactive visualization works only inside a notebook, you can either try the non-interactive matplotlib one or use the newly added option to export the result as an STL file
```python
p2v.save2stl(result['Z_surface'], 'res.stl')
```
