### ISSUE TITLE
Save the MTL file

### ISSUE THREAD

**Issue by josepereiroml** [eladrich/pix2vertex.pytorch#7]
Hello thank you for this amazing repository I want to know if it's possible to save the MTL file to use it in other programs such as Blender, thank you very much again.

**Comment by eladrich** [comment]
Should be possible, will try to add in my next update

**Comment by josepereiroml** [comment]
Thank you very much! That would be awesome.

**Comment by eladrich** [comment]
Added an option to export result as an STL file
```python
p2v.save2stl(result['Z_surface'], 'res.stl')`
```

**Comment by advaitambeskar** [comment]
Hi!
The STL export format does not include the textures and contains only the geometry of the mesh. Is there an update w.r.t the textures?
